### ISSUE TITLE
hook_field_formatter_info_alter() event

### ISSUE THREAD

**Issue by Ambient-Impact** [pdenooijer/hook_event_dispatcher#102]
Next up in my event-adding spree, I want to add [```hook_field_formatter_info_alter()```](https://api.drupal.org/api/drupal/core%21modules%21field%21field.api.php/function/hook_field_formatter_info_alter/8.8.x). Since this is part of the Field API and 2.x is splitting into more sub-modules, do we want a new ```field_event_dispatcher``` module for this?

**Comment by pdenooijer** [comment]
Yes please, sounds like a plan to me 👍

**Comment by Ambient-Impact** [comment]
(solemn salute)
