### ISSUE TITLE
All hooks in field_ui.api.php as events

### ISSUE THREAD

**Issue by Ambient-Impact** [pdenooijer/hook_event_dispatcher#103]
See [documentation for field_ui.api.php](https://api.drupal.org/api/drupal/core%21modules%21field_ui%21field_ui.api.php/8.8.x). As mentioned in #102, I assume a ```field_event_dispatcher``` module is wanted for that issue; should the Field UI stuff live under there as well, or should we create a ```field_ui_event_dispatcher```?

**Comment by pdenooijer** [comment]
I think we can add all into the field_event_dispatcher, not that many hooks anyway. We should be careful not to create to many modules as well 🙂. Should be balanced, splitting it up more is always a possibility.

**Comment by pdenooijer** [comment]
As `field_ui` is dependent on `field`, maybe a general rule of thumb is to have the base module as dispatcher name? As in the module that has no more dependencies beside drupal/core of course.

**Comment by Ambient-Impact** [comment]
That sounds reasonable, yeah. ```field_event_dispatcher``` it is!

**Comment by Ambient-Impact** [comment]
I have some work coming up, so this and further pull requests will likely be at a slower pace for the next while.

**Comment by Ambient-Impact** [comment]
Would you prefer I open a pull request for each hook, or should I bundle all of them into a single pull request?

**Comment by pdenooijer** [comment]
Single PR for all `field.api.php` is fine 🙂, as long as it can be merged quickly. So if it's easier for you to add them gradually with multiple PR that is fine as well.

**Comment by Ambient-Impact** [comment]
I'll aim for a single one, in that case. Might be faster too, to batch issues so I can fix them all at once. 😎

**Comment by Ambient-Impact** [comment]
@pdenooijer I've run into an interesting problem while implementing ```hook_field_formatter_third_party_settings_form()```: [```\Drupal\field_ui\Form\EntityViewDisplayEditForm::thirdPartySettingsForm()```](https://api.drupal.org/api/drupal/core%21modules%21field_ui%21src%21Form%21EntityViewDisplayEditForm.php/function/EntityViewDisplayEditForm%3A%3AthirdPartySettingsForm/8.8.x) automatically places each module's form elements under the module's machine name, which works fine when it's the procedural hook, but since as far as Drupal knows, it's only ```field_event_dispatcher``` that's implementing the hook, reading the third party settings no longer works in the same way. For example, I've got:

```
  $plugin->getThirdPartySetting(
    'ambientimpact_media', 'use_animated_gif_toggle'
  );
```

...in an event subscriber, which previously worked as expected in the procedural hook, but now I would have to do:

```
  $plugin->getThirdPartySetting(
    'field_event_dispatcher', 'use_animated_gif_toggle'
  );
```

...which doesn't match the Drupal core API.

I'm curious how we could get around this?

At first I thought we might be able to just extend ```EntityViewDisplayEditForm``` and override the ```thirdPartySettingsForm``` method, but I did a search and it looks like a bunch of core modules extend it, so that seems like a pain in the ass to maintain and keep up to date.

Maybe we can add an extra key to the array of ```$elements``` we return in our ```hook_field_formatter_third_party_settings_form()``` and then do a form ID alter for the entity edit form that looks for that and corrects it? We'd probably have to add an extra required parameter to ```$event->addElements()``` to specify which module the third party settings ```$elements``` are for, since I don't know how complicated that would be to get automatically, or if it's even possible.

---------------------

**Edit**: the form alter approach seems to work. Do you want me to use a procedural hook (i.e. ```field_event_dispatcher_form_entity_view_display_edit_form_alter()```) or an event subscriber for this?

**Comment by pdenooijer** [comment]
@Ambient-Impact yeah I have had a kinda similar problem with hook_theme(), as the path would be that of hook_event_dispatcher instead of the module your executing.

Seems like a good solution to me with the use of an hook. Can you make a branch/PR for that specific hook so I can review your solution?

**Comment by Ambient-Impact** [comment]
You mean a PR just for ```hook_field_formatter_third_party_settings_form()```? Sure, I can do that.

**Comment by pdenooijer** [comment]
Yeah for the combination of the hooks so it's easy to review and test 🙂

**Comment by Ambient-Impact** [comment]
For the ```hook_field_formatter_third_party_settings_form()``` tests, I'm thinking we should have at least two:

1. One that tests that all the methods return the correct data types - I'm guessing we can just rely on the explicitly defined return types and a PHP exception will get recorded by PHPUnit as a fail? There are 6 separate methods for getting all the properties, which is why I suspect this would be a good idea.

2. Another that tests actually adding form elements, as is done for a lot of the other events.

Let me know what you think.

**Comment by Ambient-Impact** [comment]
@pdenooijer The implementation of the ```hook_field_formatter_third_party_settings_form``` event (which is now merged) and that of ```hook_field_widget_third_party_settings_form``` seem to only have minor differences between them, and require the same form alter technique. Should I try to rewrite them so that they share code and tests, so as not to duplicate functionality, or should they remain totally separate?

**Comment by pdenooijer** [comment]
Yeah some re-usage of code is fine, if it ever changes we can always go back to multiple classes anyway 🙂.

**Comment by Ambient-Impact** [comment]
I've gotten the work done of merging the two, but it occurs to me that it may be better to open a pull request for the standlone ```hook_field_widget_third_party_settings_form``` and then another pull request for merging them together after that. What do you think?

**Comment by pdenooijer** [comment]
Multiple small PR >>>>>> big PR, so go for it 🙂 !

**Comment by Ambient-Impact** [comment]
So I think that wraps up the ```field_ui.api.php``` stuff. Let me know if there's anything else or if we can close the issue.

**Comment by pdenooijer** [comment]
Yep I agree 👍

**Comment by Ambient-Impact** [comment]
[![An animated fox dancing.](https://media.giphy.com/media/l3vR3FaH4adpUG9eE/source.gif)](https://giphy.com/gifs/fox-kk-dance-bounce-gif-dsi-flipnote-spinning-l3vR3FaH4adpUG9eE)
