### ISSUE TITLE
Reason for composer.lock inclusion

### ISSUE THREAD

**Issue by daFish** [pdenooijer/hook_event_dispatcher#17]
What is the reason behind the decision to check in `composer.lock`?

**Comment by pdenooijer** [comment]
Can you be more specific what you mean exactly? The composer.lock is something composer generates for me.

**Comment by daFish** [comment]
Yes, of course. 😄 
Composer generates this file to make it possible for others to install the exact dependencies as you. This makes sense in an application but not in a library context. When I require your module, composer takes also your composer.lock with the fixed dependencies into account when all dependencies and their constraints are used to determine the exact versions to install.

This can easily lead to errors when the application dependencies are conflicting with the ones from your module. So it is considered a good practice to add the `composer.lock` to your `.gitignore`.

You can read more about that topic here: https://philsturgeon.uk/php/2014/11/04/composer-its-almost-always-about-the-lock-file/

**Comment by robiningelbrecht** [comment]
I agree with Marcus. The composer.lock file should not be in the module
release.

Robin Ingelbrecht
Drupal Developer
  *EntityOne*
Ottergemsesteenweg Zuid 731 | 9000 Gent
www.entityone.be  <http://www.entityone.be/> |
robin.ingelbrecht@entityone.be
GSM: 0471 08 57 09 <https://www.entityone.be/email-cta>

**Comment by pdenooijer** [comment]
Good point, I'll remove it this weekend 👍. Never thought about it. Thanks for suggestion!

**Comment by daFish** [comment]
@pdenooijer If you don't mind an PR than I can do it.

**Comment by pdenooijer** [comment]
Sure, go ahead!

**Comment by daFish** [comment]
Already done.

**Comment by pdenooijer** [comment]
I made a new release with your fix included:
https://www.drupal.org/project/hook_event_dispatcher/releases/8.x-1.12
