### ISSUE TITLE
Add support for hook_template_preprocess_default_variables_alter

### ISSUE THREAD

**Issue by DieterHolvoet** [pdenooijer/hook_event_dispatcher#26]
Hi, could it be possible to add support for the following hook?

https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_template_preprocess_default_variables_alter/8.2.x

Thanks in advance

**Comment by pdenooijer** [comment]
Hey @DieterHolvoet, could you make a PR with the requested functionality 😉?

**Comment by DieterHolvoet** [comment]
I'm not really familiar with the codebase, but if I find the time to have a look at it I will

**Comment by pdenooijer** [comment]
Yeah, I have the time problem as well 😅.

**Comment by pdenooijer** [comment]
Fixed!

**Comment by DieterHolvoet** [comment]
Thanks, you're the best!
