### ISSUE TITLE
Provide a generic way to trigger events for entities by bundle/view mode

### ISSUE THREAD

**Issue by gertvdb** [pdenooijer/hook_event_dispatcher#42]
If I'm not mistaken, the module currently provides a node preprocess event but no event for preprocessing nodes by bundle or view mode. I think i would be great to provide such an event and make it generic so it will work on any entity. Since all entities will have at least one bundle and a view mode.

I would really like to do this (by example) : 

```
article module

/**
   * {@inheritdoc}
   */
  public static function getSubscribedEvents() {
    return [
      'hook_event_dispatcher.preprocess.node.article' => 'preprocessArticle',
      'hook_event_dispatcher.preprocess.node.article.teaser' => 'preprocessArticleTeaser',
      'hook_event_dispatcher.preprocess.node.article.preview' => 'preprocessArticlePreview',
    ];
  }

```
I tried to make a PR for this https://github.com/pdenooijer/hook_event_dispatcher/pull/41. Let me know what you think. Anyway awesome module!

**Comment by pdenooijer** [comment]
Thanks for your issue, I'll have a look at your PR 🙂!

**Comment by pdenooijer** [comment]
@gertvdb the dev version now has the possibility to specify which entity type & view mode you want to preprocess. Please check it out 🙂!

**Comment by gertvdb** [comment]
Awesome, nice work! Love the NodePreprocessEvent::name($bundle, $viewMode) to define your events.

**Comment by pdenooijer** [comment]
Good to hear you like it, please test if no error/exceptions occur, so I can make a new stable release 🙂.

**Comment by pdenooijer** [comment]
Made a pre-release/alpha version to test out 🙂! Please report back your findings!

**Comment by gertvdb** [comment]
I've adapted my old preprocess events using the alpha version in a few production sites for a while now and i'm not seeing any problems.

**Comment by pdenooijer** [comment]
Nice to hear @gertvdb, I'll upgrade the alpha version as soon as possible. Thanks for the feedback 👍

**Comment by pdenooijer** [comment]
Making a new release, so closing this.
