### ISSUE TITLE
Can ThemeEvent be used in place of hook_theme_registry_alter()?

### ISSUE THREAD

**Issue by Ambient-Impact** [pdenooijer/hook_event_dispatcher#75]
Hi there. I'm thinking about implementing an event for [```hook_theme_registry_alter()```](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Render!theme.api.php/function/hook_theme_registry_alter) but I'm wondering if it's possible to just use ```ThemeEvent::getExisting()``` in my own code? From what I can tell, it only seems to be returning a small subset of the theme implementations so a new event may be required.

**Comment by pdenooijer** [comment]
Hey @Ambient-Impact! To be honest I only know what the documentation of the hook says:
```
 * @param array $existing
 *   An array of existing implementations that may be used for override
 *   purposes. This is primarily useful for themes that may wish to examine
 *   existing implementations to extract data (such as arguments) so that
 *   it may properly register its own, higher priority implementations.
```
Of course it could also have to do with what hook is called first, if hook_event_dispatcher is earlier then other modules I guess the existing won't be that long of a list. Seeing it start with an `h` and this letter is fairly early in the alphabet I guess that also has something to do with the small list.

I think you do need a hook_theme_registry_alter() for that.

Hope this helps.

**Comment by Ambient-Impact** [comment]
Fair enough. I'll look into implementing the event when I get a chance, along with a few others. 🙃

----------------

How do you have this module set up locally to work on? I ask because I'm still trying to figure out how to both list this as a dependency in Composer and have it checked out as a repository so that I can commit and push my changes? You can see part of my process in my [framework's readme](https://github.com/Ambient-Impact/drupal-modules/blob/8.x-1.x/readme.md#using-composer), and I've trying this in my root ```composer.json``` ```"repositories"``` section, but it doesn't seem to do anything:

```
    "drupal/hook_event_dispatcher": {
      "type": "package",
      "package": {
        "name": "drupal/hook_event_dispatcher",
        "type": "drupal-module",
        "version": "1.x-dev",
        "source": {
          "url": "https://github.com/Ambient-Impact/hook_event_dispatcher.git",
          "type": "git",
          "reference": "8.x-1.x"
        }
      }
    }
```

**Comment by pdenooijer** [comment]
I would just add it with composer as a submodule by using `--prefer-source` when you require the module.

**Comment by pdenooijer** [comment]
Closing this as there is no more activity.

**Comment by Ambient-Impact** [comment]
No worries, thanks!
