### ISSUE TITLE
Media oEmbed event + PHPUnit autoload issue

### ISSUE THREAD

**Issue by Ambient-Impact** [pdenooijer/hook_event_dispatcher#91]
Hi there. I started implementing [```hook_oembed_resource_url_alter()```](https://api.drupal.org/api/drupal/core%21modules%21media%21media.api.php/function/hook_oembed_resource_url_alter/8.8.x). Despite still being optional, Drupal core's media initiative has really been pushing it as the recommended way to handle media like remote videos, so would it make sense to have such an event in ```hook_event_dispatcher``` itself rather than a submodule? I'm leaning towards yes, but would like to know what the preferred location for the event would be.

----------------

Also, while working on the tests for the event, I discovered that PHPUnit is throwing this error:
```
Error: Class 'Drupal\media\OEmbed\Provider' not found
```

...which is odd, because the class is there, and I assumed the Composer autoloader should have picked it up when I ran ```composer install``` in the module's directory. Do I have to add something to ```phpunit.autoload.php``` to have it be used?

**Comment by Ambient-Impact** [comment]
🤦‍♀ Turns out I had to add ```"Drupal\\media\\": "vendor/drupal/core/modules/media/src/"``` to ```autoload-dev``` in ```composer.json```. Whoops.

**Comment by pdenooijer** [comment]
Hey @Ambient-Impact, please add a submodule as it depends on media to be enabled. I am currently splitting up most of the events so you can enable what you need for version 2 of this module and be dependent on PHP7.1 as Drupal core does the same at the moment.

**Comment by Ambient-Impact** [comment]
Will do. Should I name it ```media_event_dispatcher```, or do you have another naming convention in mind?

**Comment by pdenooijer** [comment]
Sounds fine, so all media related events can be grouped there 👍

**Comment by Ambient-Impact** [comment]
[![An exaggerated salute in front of an American flag](https://media.giphy.com/media/3osxYrgM8gi9CDjcPu/source.gif)](https://giphy.com/gifs/broadcity-broad-city-ilana-glazer-hail-to-the-kween-3osxYrgM8gi9CDjcPu)

**Comment by Ambient-Impact** [comment]
Another question: should I add the event name constant to ```HookEventDispatcherInterface``` or create a new ```MediaEventDispatcherInterface``` in the new module and place it there?

**Comment by pdenooijer** [comment]
Add to the `HookEventDispatcherInterface` is fine 👍

**Comment by pdenooijer** [comment]
PR 92 merged so we can close this 🙂
