### ISSUE TITLE
2.x - fatal error due to hook_event_dispatcher_views_post_render $output param actually being an array rather than string

### ISSUE THREAD

**Issue by Ambient-Impact** [pdenooijer/hook_event_dispatcher#93]
Title sums it up. It seems that the documentation for ```hook_views_post_render``` is incorrect, and ```$output``` is passed as render array as reported in [this core issue](https://www.drupal.org/project/drupal/issues/2793169). I can make a pull request fixing this if you'd like.

**Comment by pdenooijer** [comment]
Great find, yes please 👍

**Comment by Ambient-Impact** [comment]
Will do. We'd also want to update ```Drupal\Tests\hook_event_dispatcher\Unit\Views::testPostRenderEvent()``` to test ```$output``` as an array, right?

**Comment by pdenooijer** [comment]
Yes, update the test as well to make sure Travis stays green 🙂
