### ISSUE TITLE
hook_media_source_info_alter() event

### ISSUE THREAD

**Issue by Ambient-Impact** [pdenooijer/hook_event_dispatcher#99]
Since [media.api.php](https://api.drupal.org/api/drupal/core%21modules%21media%21media.api.php/8.7.x) only defines two hooks at the moment and I've already implemented one, I figured I'd implement the other one as well for completion's sake. I've already got most of it done yesterday, so I should be able to open a pull request today if that's alright.

**Comment by pdenooijer** [comment]
Sounds like a plan to me 👍
